artipie/http

src/main/java/com/artipie/http/Front.java
src/main/java/com/artipie/http/HttpException.java
src/main/java/com/artipie/http/Request.java
src/main/java/com/artipie/http/Response.java
src/main/java/com/artipie/http/package-info.java
src/test/java/com/artipie/http/package-info.java

#1 - base HTTP interfaces:
- request
- response
- front

Base HTTP interfaces

---

pom.xml
src/main/java/com/artipie/http/Request.java
src/main/java/com/artipie/http/tk/TkRequest.java
src/main/java/com/artipie/http/tk/package-info.java

#3 - added Takes implementation of `Request`

Takes request wrapper

---

pom.xml
src/main/java/com/artipie/http/tk/TkRequest.java
src/test/java/com/artipie/http/tk/TkRequestTest.java

#6 - added unit test for takes request

Unit test for takes request

---

pom.xml
src/main/java/com/artipie/http/Request.java
src/main/java/com/artipie/http/tk/TkRequest.java
src/test/java/com/artipie/http/tk/TkRequestTest.java
src/test/java/com/artipie/http/tk/package-info.java

#7 - implemented request body publisher and unit test. Enabled qulice.

Request body with test

---

.rultor.yml

Added rultor config for release

Rultor config for release

---

src/main/java/com/artipie/http/RequestLine.java
src/test/java/com/artipie/http/RequestLineTest.java

Request line would simplify request line formation by a server

add Request Line

---

pom.xml

Fixed javadoc generating problem by updating parent pom parent pom v0.2.1

Bump parent pom v0.2.1

---

.rultor.yml

Enabled merge script, updated arcs

Fixed rultor config

---

pom.xml
src/main/java/com/artipie/http/Response.java
src/main/java/com/artipie/http/hm/RsHasStatus.java
src/main/java/com/artipie/http/hm/package-info.java
src/main/java/com/artipie/http/rs/RsWithStatus.java
src/main/java/com/artipie/http/rs/StatusResponse.java
src/main/java/com/artipie/http/rs/package-info.java
src/test/java/com/artipie/http/rs/RsWithStatusTest.java
src/test/java/com/artipie/http/rs/StatusResponseTest.java
src/test/java/com/artipie/http/rs/package-info.java

#17 - added response with status and hamcrest matcher to verify response status

Response with status and matcher

---

src/main/java/com/artipie/http/rq/RequestLineFrom.java

Methods should  not throw any checked exceptions

Simplify RequestLineFrom

---

pom.xml
src/main/java/com/artipie/http/rs/RsWithBody.java

#29 - added response with string and `ByteBuffer` body.

Added response with body

---

pom.xml
src/main/java/com/artipie/http/rq/RqHeaders.java
src/test/java/com/artipie/http/rq/RqHeadersTest.java

#48 - added two header helper objects: `RqHeaders` as `List<String>` and `RqHeaders.Single` as `Text`.

Implemented headers helper

---

pom.xml
src/main/java/com/artipie/http/Connection.java
src/main/java/com/artipie/http/Response.java
src/main/java/com/artipie/http/Slice.java
src/main/java/com/artipie/http/hm/RsHasBody.java
src/main/java/com/artipie/http/hm/RsHasStatus.java
src/main/java/com/artipie/http/rq/RqMultipart.java
src/main/java/com/artipie/http/rq/RqPart.java
src/main/java/com/artipie/http/rs/RsWithBody.java
src/main/java/com/artipie/http/rs/RsWithStatus.java
src/test/java/com/artipie/http/hm/RsHasBodyTest.java

#57 - updated to parent `0.3`, downgraded to JDK8

Updated to latest parent pom

---

src/main/java/com/artipie/http/rq/RequestLineFrom.java
src/main/java/com/artipie/http/rq/RqMethod.java
src/test/java/com/artipie/http/rq/RequestLineFromTest.java

Added RsMethod class to represent HTTP method.

Added RsMethod class with all HTTP methods

---

src/main/java/com/artipie/http/Connection.java
src/main/java/com/artipie/http/Response.java
src/main/java/com/artipie/http/hm/RsHasBody.java
src/main/java/com/artipie/http/hm/RsHasStatus.java
src/main/java/com/artipie/http/rs/RsStatus.java
src/main/java/com/artipie/http/rs/RsWithBody.java
src/main/java/com/artipie/http/rs/RsWithStatus.java
src/test/java/com/artipie/http/hm/RsHasBodyTest.java
src/test/java/com/artipie/http/rs/RsWithStatusTest.java

Added RsStatus class to represent HTTP response status code with some commonly used statuses predefined.

Added RsStatus class with most commonly used HTTP response status codes

---

src/main/java/com/artipie/http/rt/RtRule.java
src/main/java/com/artipie/http/rt/SliceRoute.java
src/main/java/com/artipie/http/rt/package-info.java

#51 - added `Slice` implementation with routing support

Added initial routing slice objects

---

pom.xml
src/main/java/com/artipie/http/async/AsyncResponse.java
src/main/java/com/artipie/http/slice/ContentWithSize.java
src/main/java/com/artipie/http/slice/KeyFromPath.java
src/main/java/com/artipie/http/slice/SliceDownload.java
src/main/java/com/artipie/http/slice/SliceUpload.java
src/main/java/com/artipie/http/slice/package-info.java
src/test/java/com/artipie/http/slice/KeyFromPathTest.java
src/test/java/com/artipie/http/slice/SliceDownloadTest.java
src/test/java/com/artipie/http/slice/SliceUploadTest.java
src/test/java/com/artipie/http/slice/package-info.java

#64 - added upload and download slices to work with `Storage` by `Key` from path

Upload and download slices

---

src/main/java/com/artipie/http/rt/SliceRoute.java

For #72: Removed null from SliceRoute using streams

For #72: removed null from SliceRoute

---

src/main/java/com/artipie/http/stream/ByteByByteSplit.java

This pull request resolves #67

Synchronisation improvements

---

src/main/java/com/artipie/http/slice/SliceSimple.java

Add slicee simple from the ticket #73

slice simple object

---

src/main/java/com/artipie/http/rq/Multipart.java

Implement subscriber part

---

src/main/java/com/artipie/http/rq/Multipart.java
src/main/java/com/artipie/http/rq/PartFromPublisher.java

This pull request is blocked by #91, and can't be reviewed or merged before. Related to #32

Implement publisher part

---

README.md
src/main/java/com/artipie/http/auth/Identities.java
src/main/java/com/artipie/http/auth/Permission.java
src/main/java/com/artipie/http/auth/Permissions.java
src/main/java/com/artipie/http/auth/SliceAuth.java
src/main/java/com/artipie/http/auth/package-info.java
src/test/java/com/artipie/http/auth/SliceAuthTest.java
src/test/java/com/artipie/http/auth/package-info.java

#97 - added authentication interface: `Identities`, authorization provider `Permissions` and `Slice` to perform auth checks: `SliceAuth`.

Authentication and authorization interfaces

---

src/main/java/com/artipie/http/hm/RsHasHeaders.java
src/test/java/com/artipie/http/hm/RsHasHeadersTest.java

Closes #100 
Added matcher for response headers and tests for it

#100 - Added RsHasHeaders matcher

---

src/main/java/com/artipie/http/slice/LoggingSlice.java
src/test/java/com/artipie/http/slice/LoggingSliceTest.java

Part of #102 
Added Slice with logging, that could be composed with other Slices

#102 - Added LoggingSlice

---

src/main/java/com/artipie/http/async/AsyncSlice.java
src/test/java/com/artipie/http/async/AsyncResponseTest.java
src/test/java/com/artipie/http/async/AsyncSliceTest.java
src/test/java/com/artipie/http/async/package-info.java

Closes #59 
Added tests and important typing improvements that make these classes convenient to use in adapters.

#59 - Improved types in AsyncResponse & AsyncSlice. Added tests

---

README.md

Made several cosmetic corrections in readme.

Cosmetic corrections in readme

---

src/main/java/com/artipie/http/rq/RqMethod.java
src/main/java/com/artipie/http/rs/RsStatus.java

Closes #106 
Added RsStatus values for codes 204 and 416 & PATCH method support. They are needed in Docker registry API

#106 - Added RsStatus values for codes 204 and 416 & RqMethod.PATCH

---

src/main/java/com/artipie/http/auth/Authentication.java
src/main/java/com/artipie/http/auth/BasicIdentities.java
src/main/java/com/artipie/http/auth/IdentityProvider.java
src/test/java/com/artipie/http/auth/BasicIdentitiesTest.java

Introduced the Basic Authentication for http part.
Common interface to verify user is able to operate with Artipie.

Basic Auth, tests

---

src/main/java/com/artipie/http/Connection.java
src/main/java/com/artipie/http/Headers.java
src/main/java/com/artipie/http/Response.java
src/main/java/com/artipie/http/hm/RsHasBody.java
src/main/java/com/artipie/http/hm/RsHasHeaders.java
src/main/java/com/artipie/http/hm/RsHasStatus.java
src/main/java/com/artipie/http/rs/RsWithBody.java
src/main/java/com/artipie/http/rs/RsWithHeaders.java
src/main/java/com/artipie/http/rs/RsWithStatus.java
src/main/java/com/artipie/http/rs/StandardRs.java
src/main/java/com/artipie/http/slice/LoggingSlice.java
src/test/java/com/artipie/http/hm/RsHasBodyTest.java
src/test/java/com/artipie/http/rq/MultipartTest.java

Closes #122 
Added `Headers ` interface, `Headers.From` for creating simple instances and their usage

#122 - Added Headers abstraction

---

src/main/java/com/artipie/http/rq/RequestLineFrom.java
src/test/java/com/artipie/http/rq/RequestLineFromTest.java

For #24 added idx check into `RequestLineFrom#part` and some tests.

#24: idx check

---

src/main/java/com/artipie/http/hm/IsHeader.java
src/test/java/com/artipie/http/hm/IsHeaderTest.java

Closes #120 
Added IsHeader matcher to match response headers along with tests

#120 - Added IsHeader matcher

---

src/main/java/com/artipie/http/slice/LoggingSlice.java

change logging source in logging slice to underlying slice

---

src/main/java/com/artipie/http/async/AsyncResponse.java

Improves AsyncReponse user experience.

Extend AsyncResponse with constructor which accepts a single

---

src/main/java/com/artipie/http/rs/Header.java
src/test/java/com/artipie/http/rs/HeaderTest.java

Closes #131 
Added Header class

#131 - Added Header class

---

src/main/java/com/artipie/http/slice/SliceWithHeaders.java
src/test/java/com/artipie/http/slice/SliceWithHeadersTest.java

Closes #132. I've added slice decorator `SliceWithHeaders`.

#132 Slice with headers

---

src/main/java/com/artipie/http/auth/BasicIdentities.java

Made ctor public to call from outside (from adapters).

---

src/main/java/com/artipie/http/Response.java
src/main/java/com/artipie/http/rs/RsFull.java

Closes #139 
Added `Response.Wrap` abstract decorator and example usage in `RsFull`

#139 - Added Response.Wrap

---

src/main/java/com/artipie/http/rs/Header.java

#141 - Added Header.Wrap

---

pom.xml
src/main/java/com/artipie/http/rs/RsWithBody.java
src/test/java/com/artipie/http/rs/RsWithBodyTest.java

Created test for `RsWithBody` and removed todo.

For #37 test for RsWithBody

---

src/main/java/com/artipie/http/rs/RsStatus.java

Closes #145 
Added 413 and 411 HTTP response status codes.

#145 - Added `Content-Length` checking related HTTP status codes

---

src/main/java/com/artipie/http/rs/Header.java

#141 - Fixed Header.Wrap to be public

---

pom.xml
src/main/java/com/artipie/http/auth/Authentication.java
src/main/java/com/artipie/http/auth/BasicIdentities.java
src/test/java/com/artipie/http/auth/BasicIdentitiesTest.java

#151 - find user by username and password or fail authentication if not found to return `401` error

Find user by credentials

---

src/main/java/com/artipie/http/auth/Authentication.java

Corrected java doc in `Authentication.java` to avoid future misunderstanding as in https://github.com/artipie/artipie/pull/157.

Authentication.java javadoc correction

---

src/main/java/com/artipie/http/auth/SliceAuth.java
src/test/java/com/artipie/http/auth/SliceAuthTest.java

Closes #156 
Added WWW-Authenticate header to SliceAuth response

#156 - Added WWW-Authenticate header to SliceAuth response

---

src/main/java/com/artipie/http/slice/LoggingSlice.java
src/test/java/com/artipie/http/slice/LoggingSliceTest.java

Closes #149 
Added exception logging to `LoggingSlice`

#149 - Exception logging in LoggingSlice

---

src/main/java/com/artipie/http/hm/ResponseMatcher.java
src/test/java/com/artipie/http/hm/ResponseMatcherTest.java
src/test/java/com/artipie/http/rs/RsWithBodyTest.java
src/test/java/com/artipie/http/slice/SliceDownloadTest.java

Created response matcher for #153. This the same as #155

#153 - response matcher and test created

---

src/main/java/com/artipie/http/rt/RtPath.java
src/main/java/com/artipie/http/rt/RtRulePath.java
src/main/java/com/artipie/http/rt/SliceRoute.java

 (#127) - Extract Path interface for SliceRoute

---

src/main/java/com/artipie/http/rs/ContentLength.java
src/test/java/com/artipie/http/rs/ContentLengthTest.java

Part of #174 
Added ContentLength header class

#174 - Added ContentLength header class

---

src/main/java/com/artipie/http/rs/ContentType.java
src/test/java/com/artipie/http/rs/ContentTypeTest.java

Part of #174 
Added `ContentType` header class that can be build from concrete value or from headers

#174 - Added ContentType header class

---

src/main/java/com/artipie/http/rs/RsStatus.java
src/test/java/com/artipie/http/rs/RsStatusByCodeTest.java

I've introduced class `RsStatus.ByCode` to obtain `RsStatus` instance by code.

Introduced RsStatus.ByCode

---

src/main/java/com/artipie/http/rs/Location.java
src/test/java/com/artipie/http/rs/LocationTest.java

Closes #174
Added Location header class that can be built from value and from headers

#174 - Added Location header class

---

pom.xml
src/main/java/com/artipie/http/group/GroupConnection.java
src/main/java/com/artipie/http/group/GroupResponse.java
src/main/java/com/artipie/http/group/GroupResult.java
src/main/java/com/artipie/http/group/GroupResults.java
src/main/java/com/artipie/http/group/GroupSlice.java
src/main/java/com/artipie/http/group/package-info.java

#169 - implemented initial version of group slice

Group slices

---

pom.xml
src/main/java/com/artipie/http/hm/RsHasHeaders.java
src/main/java/com/artipie/http/rs/RsWithBody.java
src/main/java/com/artipie/http/rs/RsWithHeaders.java
src/test/java/com/artipie/http/hm/ResponseMatcherTest.java
src/test/java/com/artipie/http/rs/RsWithBodyTest.java

#176 - added `Content-Length` headers to `RsWithBody`

Response content-length headers

---

src/main/java/com/artipie/http/auth/SliceAuth.java
src/main/java/com/artipie/http/rs/WwwAuthenticate.java
src/test/java/com/artipie/http/rs/WwwAuthenticateTest.java

Part of #185 
Added WWW-Authenticate header class that could be build from raw data and extracted from headers collection

#185 - Added WWW-Authenticate header class

---

src/main/java/com/artipie/http/Headers.java
src/main/java/com/artipie/http/rs/RsWithHeaders.java
src/test/java/com/artipie/http/HeadersFromTest.java
src/test/java/com/artipie/http/package-info.java

Part of #189 
Added constructors to `Headers.From` class to build `Headers` from collection and additional header(s)

#189 - Additional Headers constructors

---

src/main/java/com/artipie/http/headers/WwwAuthenticate.java
src/test/java/com/artipie/http/headers/WwwAuthenticateTest.java

Closes #185 
Parsing WWW-Authenticate header implemented with extraction of scheme and params

#185 - Parsing value of WWW-Authenticate header

---

src/main/java/com/artipie/http/auth/Authentication.java
src/test/java/com/artipie/http/auth/AuthenticationTest.java

Closes #198 
Added `Authentication.Single` and `Authentication.Wrap`

#198 - Added Authentication.Single and Authentication.Wrap

---

src/main/java/com/artipie/http/auth/Permissions.java
src/test/java/com/artipie/http/auth/PermissionsTest.java

Closes #200 
Added `Permissions.Single` and `Permissions.Wrap` along with tests

#200 - Added Permissions.Single and Permissions.Wrap

---

pom.xml
src/main/java/com/artipie/http/async/AsyncResponse.java
src/main/java/com/artipie/http/group/GroupConnection.java
src/main/java/com/artipie/http/group/GroupResponse.java
src/main/java/com/artipie/http/group/GroupResult.java
src/main/java/com/artipie/http/group/GroupResults.java
src/main/java/com/artipie/http/hm/RsHasBody.java
src/main/java/com/artipie/http/hm/SliceHasResponse.java
src/main/java/com/artipie/http/rs/RsWithBody.java
src/main/java/com/artipie/http/rs/StandardRs.java
src/test/java/com/artipie/http/group/GroupSliceTest.java
src/test/java/com/artipie/http/group/package-info.java

#203 - added a unit test for group slice to verify that slice returns expected status code from grouped items.

Unit test for group slice

---

src/main/java/com/artipie/http/rs/RsStatus.java

artipie/artipie#382 - added `100` and `417` statuses to respond for `Expect` requests

Expected conditional headers

---

pom.xml
src/main/java/com/artipie/http/hm/SliceHasResponse.java
src/main/java/com/artipie/http/hm/StatefulResponse.java
src/main/java/com/artipie/http/rs/common/RsJson.java
src/main/java/com/artipie/http/rs/common/package-info.java
src/test/java/com/artipie/http/rs/common/RsJsonTest.java
src/test/java/com/artipie/http/rs/common/package-info.java

#210 - moved `RsJson` from `artipie/artipie` added tests, fixed response matchers.

Introduced response for JsonStructure

---

src/main/java/com/artipie/http/rq/RequestLinePrefix.java
src/test/java/com/artipie/http/rq/RequestLinePrefixTest.java

To close #202 added class to obtain request prefix from `X-FullPath` and request line.

#202 - request prefix

---

src/main/java/com/artipie/http/rs/RsWithBody.java
src/main/java/com/artipie/http/rs/common/RsJson.java
src/main/java/com/artipie/http/rs/common/RsText.java
src/test/java/com/artipie/http/rs/common/RsJsonTest.java
src/test/java/com/artipie/http/rs/common/RsTextTest.java

#210 - plain text responses with encoding from `CharSequence`

Text responses

---

src/main/java/com/artipie/http/rs/RsStatus.java
src/test/java/com/artipie/http/rs/RsStatusTest.java

For #196 classification methods `bool isClientError()`, `bool isServerError()`, `bool isError()` added

#196 classification methods added

---

src/main/java/com/artipie/http/group/GroupSlice.java

#206 - send only read requests to group slices, all write/modify requests are going to first slice only

Fixed group slice

---

pom.xml
src/main/java/com/artipie/http/rt/ByMethodsRule.java
src/main/java/com/artipie/http/rt/RlByMethods.java
src/main/java/com/artipie/http/rt/RtRule.java
src/test/java/com/artipie/http/rt/ByMethodsRuleTest.java
src/test/java/com/artipie/http/rt/package-info.java

#220 - refactored routing rule by methods

Rule by methods

---

src/main/java/com/artipie/http/auth/Authentication.java
src/test/java/com/artipie/http/auth/AuthenticationTest.java

Closes #222 
Added `Authentication.Joined` class

#222 - Added Authentication.Joined

---

src/main/java/com/artipie/http/auth/Action.java
src/test/java/com/artipie/http/auth/ActionTest.java

Part of #238 
Created `Action` interface and its enum implementation.

#238 - created `Action` interface and its implementation

---

src/main/java/com/artipie/http/auth/Authentication.java
src/main/java/com/artipie/http/auth/BasicIdentities.java
src/test/java/com/artipie/http/auth/AuthenticationTest.java
src/test/java/com/artipie/http/auth/BasicIdentitiesTest.java

Closes #241
Added `Authentication.User`class and changed `Authentication#user` signature.

#241 - User groups

---

src/main/java/com/artipie/http/auth/BasicAuthSlice.java
src/main/java/com/artipie/http/auth/BasicIdentities.java
src/main/java/com/artipie/http/auth/Identities.java
src/main/java/com/artipie/http/headers/Authorization.java
src/test/java/com/artipie/http/auth/BasicAuthSliceTest.java
src/test/java/com/artipie/http/auth/BasicIdentitiesTest.java

Closes #247 
I've created `BasicAuthSlice` from `SliceAuth` and `BasicIdentities` and deprecated `Identities`, `SliceAuth` and `BasicIdentities`

#247 - created BasicAuthSlice

---

src/main/java/com/artipie/http/auth/Authentication.java

Closes #249 
Created `Authentication.Anonymous`

#249 - Authentication.Anonymous created

---

src/main/java/com/artipie/http/rt/RtRule.java
src/test/java/com/artipie/http/rt/RtRuleByHeaderTest.java

Closes #253 
Implemented rule by headers.

#253 - RtRule.ByHeader created

---

src/main/java/com/artipie/http/rt/RtRule.java
src/test/java/com/artipie/http/rt/RtRuleByHeaderTest.java

Closes #253 
Added regex for header value and corresponding tests.

#253 - added header value regex to RtRule.ByHeader

---

src/main/java/com/artipie/http/group/GroupResponse.java
src/test/java/com/artipie/http/group/GroupSliceTest.java

Closes #256 
Group slice error handling

#256 - Group slice error handling

---

src/main/java/com/artipie/http/auth/Permission.java
src/test/java/com/artipie/http/auth/PermissionAllTest.java

Part of #258 
Added `Permission.All`

#258 - Added Permission.All

---

src/main/java/com/artipie/http/auth/BasicAuthSlice.java
src/test/java/com/artipie/http/auth/BasicAuthSliceTest.java

Part of #261 
Lazy authentication in `BasicAuthSlice`

#261 - Lazy authentication in BasicAuthSlice

---

src/main/java/com/artipie/http/auth/AuthScheme.java
src/main/java/com/artipie/http/auth/AuthSlice.java
src/main/java/com/artipie/http/auth/BasicAuthScheme.java
src/main/java/com/artipie/http/headers/Authorization.java

Part of #261 
Extracted `AuthSlice` and `AuthScheme` from `BasicAuthSlice`

#261 - Extracted AuthSlice and AuthScheme from BasicAuthSlice

---

src/main/java/com/artipie/http/auth/BearerAuthScheme.java
src/main/java/com/artipie/http/auth/TokenAuthentication.java
src/main/java/com/artipie/http/headers/Authorization.java
src/test/java/com/artipie/http/auth/BearerAuthSchemeTest.java

Part of #261 
Added `BearerAuthScheme`

#261 - Added BearerAuthScheme

---

src/main/java/com/artipie/http/auth/BearerAuthScheme.java
src/test/java/com/artipie/http/auth/BearerAuthSchemeTest.java

Part of #261 
Added challenge to `BearerAuthScheme`

#261 - Added challenge to BearerAuthScheme

---

src/main/java/com/artipie/http/auth/Permission.java
src/test/java/com/artipie/http/auth/PermissionAnyTest.java

Closes #268 
Added `Permission.Any` implementation and test

#268 - Permission.Any added

---

src/main/java/com/artipie/http/auth/AuthScheme.java
src/main/java/com/artipie/http/auth/AuthSlice.java
src/main/java/com/artipie/http/auth/BasicAuthScheme.java
src/main/java/com/artipie/http/auth/BearerAuthScheme.java
src/main/java/com/artipie/http/auth/TokenAuthentication.java
src/test/java/com/artipie/http/auth/BearerAuthSchemeTest.java

Closes #261 
Async `AuthScheme` and `TokenAuthentication`

#261 - Async AuthScheme and TokenAuthentication

---

src/main/java/com/artipie/http/auth/BasicAuthScheme.java
src/main/java/com/artipie/http/auth/BearerAuthScheme.java
src/main/java/com/artipie/http/headers/Authorization.java
src/test/java/com/artipie/http/headers/AuthorizationBasicTest.java
src/test/java/com/artipie/http/headers/AuthorizationBearerTest.java
src/test/java/com/artipie/http/headers/AuthorizationTest.java

Closes #194
Authorization header parsing extracted

#194 - Authorization header parsing extracted

---

src/main/java/com/artipie/http/auth/JoinedPermissions.java
src/test/java/com/artipie/http/auth/JoinedPermissionsTest.java

Closes #273 
`JoinedPermissions` added

#273 - JoinedPermissions added

---

src/main/java/com/artipie/http/rq/RqParams.java
src/test/java/com/artipie/http/rq/RqParamsTest.java

Closes #276 
`RqParams` class added

#276 - RqParams class added

---

src/main/java/com/artipie/http/auth/AuthScheme.java

Closes #278 
Added `AuthScheme.Fake`

#278 - AuthScheme.Fake added

---

src/main/java/com/artipie/http/misc/RandomFreePort.java
src/main/java/com/artipie/http/misc/package-info.java
src/test/java/com/artipie/http/misc/RandomFreePortTest.java
src/test/java/com/artipie/http/misc/package-info.java

Closes #283 
Added class for obtaining random free port.

#283 - Obtain random free port

---

src/main/java/com/artipie/http/rs/RsStatus.java

Added 421 and 429 http response statuses

---

src/main/java/com/artipie/http/headers/ContentDisposition.java
src/main/java/com/artipie/http/headers/ContentFileName.java
src/main/java/com/artipie/http/slice/SliceDownload.java
src/test/java/com/artipie/http/headers/ContentDispositionTest.java
src/test/java/com/artipie/http/headers/ContentFileNameTest.java
src/test/java/com/artipie/http/slice/SliceDownloadTest.java

Per #212:
- Introduce `ContentDispostition` & `ContentFileName`
- Add this header during download

#212: Add Content-Disposition header for a download slice

---

pom.xml
src/main/java/com/artipie/http/servlet/ServletConnection.java
src/main/java/com/artipie/http/servlet/ServletSliceWrap.java
src/main/java/com/artipie/http/servlet/package-info.java
src/test/java/com/artipie/http/servlet/package-info.java

For #289 - added slice wrappers for servlet requests,
added connection implementation based on servlet response back-end

Added servlet slice adapters

---

pom.xml
src/test/java/com/artipie/http/servlet/ServletWrapITCase.java

Closes #289 - added integration test for servlet slice wrapper
based on embedded Jetty server.

Added test for servlet wrapper

---

src/main/java/com/artipie/http/headers/Accept.java
src/test/java/com/artipie/http/headers/AcceptTest.java

Closes #297 
Added class to parse `Accept` header and corresponding test.

Added class to parse `Accept` header

---

src/main/java/com/artipie/http/rq/MultiParts.java
src/main/java/com/artipie/http/rq/RqMultipart.java

For #299 - added base classes for multipart request parsing

Base multipart classes skeleton

---

src/main/java/com/artipie/http/rq/ByteBufferTokenizer.java
src/test/java/com/artipie/http/rq/ByteBufferTokenizerTest.java

For #299 - added class to split chunks of bytebuffers
to stream of chunks of bytebuffers separated by delimiter

Added bytebuffer tokenizer with test

---

src/main/java/com/artipie/http/rq/multipart/MultipartHeaders.java
src/test/java/com/artipie/http/rq/multipart/MultipartHeadersTest.java

For #229 - added classes to build multipart request headers
from `ByteBuffer` chunks.

Added multipart headers builder

---

pom.xml
src/main/java/com/artipie/http/ArtipieHttpException.java
src/main/java/com/artipie/http/rs/common/RsError.java
src/test/java/com/artipie/http/rs/common/RsErrorTest.java

Closes #319 - added `ArtipieHttpException` with status code,
and `RsError` to create HTTP response from this exception.

Added HTTP exception and error response

---

src/main/java/com/artipie/http/misc/Pipeline.java
src/main/java/com/artipie/http/rq/multipart/Completion.java
src/main/java/com/artipie/http/rq/multipart/MultiParts.java

Added TCK for multipart, fixed publishers

fix(multipart): using pipeline

---

pom.xml
src/main/java/com/artipie/http/slice/SliceListing.java
src/test/java/com/artipie/http/slice/SliceDownloadTest.java
src/test/java/com/artipie/http/slice/SliceListingTest.java

Add unit tests for text and json mime types
Close: #426

test: add test for SliceListing

---

pom.xml
src/main/java/com/artipie/http/slice/ListingFormat.java
src/test/java/com/artipie/http/slice/ListingFormatTest.java
src/test/java/com/artipie/http/slice/SliceListingTest.java

implement HTML format for slice listing and tests for this
close: #430

feat: add HTML standard format for ListingFormat

---

src/main/java/com/artipie/security/policy/YamlPolicyFactory.java
src/test/java/com/artipie/security/policy/PoliciesLoaderTest.java
src/test/java/com/artipie/security/policy/YamlPolicyFactoryTest.java

feat: rename policy
