artipie/http

src/main/java/com/artipie/http/hm/RsHasBody.java
src/test/java/com/artipie/http/hm/RsHasBodyTest.java
src/test/java/com/artipie/http/hm/package-info.java

Added convenient hamcrest matcher to check response body in unit tests, similiar to existing `RsHasCode`.

Added RsHasBody

---

src/main/java/com/artipie/http/rs/RsWithBody.java

#29 - changed primary constructor from `RsWithBody(ByteBuffer)` to `RsWithBody(Flow.Publisher<ByteBuffer>)`. Added few secondary constructors.

Added RsWithBody constructors

---

pom.xml
src/main/java/com/artipie/http/async/AsyncSlice.java
src/main/java/com/artipie/http/async/RsAsync.java
src/main/java/com/artipie/http/async/package-info.java

#41 - added async implementations for `Slice` and `Response` based on `CompletionStage`, returning 500 error in case of unhandled exception in `CompletionStage`.

Async implementations of slice and response

---

src/main/java/com/artipie/http/stream/ByteByByteSplit.java
src/test/java/com/artipie/http/stream/ByteByByteSplitTest.java

For now, stream splitter does now work correctly with delimiters of size 2 or more. This PR fixes the problem

Split improvements

---

pom.xml
src/main/java/com/artipie/http/hm/RsHasBody.java
src/test/java/com/artipie/http/hm/RsHasBodyTest.java

Closes issue #86 
Added mark() and reset() calls to RsHasBody, so buffers remain unchanged after matching

#86 - Mark & reset buffers in RsHasBody

---

src/main/java/com/artipie/http/Response.java
src/main/java/com/artipie/http/rs/RsWithBody.java
src/main/java/com/artipie/http/rs/RsWithStatus.java
src/main/java/com/artipie/http/rs/StandardRs.java

Created `Response#NOT_FOUND`, this object will help as get rid of utility class in npm-proxy-adapter (https://github.com/artipie/npm-proxy-adapter/pull/1)

Not found response created

---

src/main/java/com/artipie/http/Headers.java
src/main/java/com/artipie/http/hm/RsHasHeaders.java
src/main/java/com/artipie/http/rs/RsWithHeaders.java

Closes #135 
Var args constructors in RsWithHeaders, Headers.From and RsHasHeaders classes

#135 - Var args constructors in headers classes

---

src/main/java/com/artipie/http/rq/RequestLine.java
src/test/java/com/artipie/http/rq/RequestLineTest.java

Closes #187 
Default HTTP version in `RequestLine` is `HTTP/1.1` and constructor accepts `RqMethod` as method argument.

#187 - Default HTTP version in RequestLine

---

src/main/java/com/artipie/http/hm/ResponseMatcher.java
src/main/java/com/artipie/http/hm/RsHasHeaders.java
src/test/java/com/artipie/http/hm/ResponseMatcherTest.java
src/test/java/com/artipie/http/hm/RsHasHeadersTest.java

Closes #214 
Better types and more constructors in `RsHasHeaders` and `ResponseMatcher`.

#214 - Better types and more constructors header matchers

---

src/main/java/com/artipie/http/slice/ContentWithSize.java

Made contractor public in `ContentWithSize`, this class can be very useful in adapters to save content to storage.

Public ctor in ContentWithSize

---

src/main/java/com/artipie/http/auth/Permission.java
src/test/java/com/artipie/http/auth/PermissionByNameTest.java
src/test/java/com/artipie/http/auth/SliceAuthTest.java

Closes #238 
I've change `Permission.ByName` to use `Action` interface instead of string action representation.

#238 - added `Action` to `Permission.ByName`

---

src/main/java/com/artipie/http/auth/Authentication.java
src/main/java/com/artipie/http/auth/BasicIdentities.java
src/main/java/com/artipie/http/auth/Identities.java
src/main/java/com/artipie/http/auth/Permission.java
src/main/java/com/artipie/http/auth/Permissions.java
src/main/java/com/artipie/http/auth/SliceAuth.java
src/test/java/com/artipie/http/auth/BasicIdentitiesTest.java
src/test/java/com/artipie/http/auth/PermissionByNameTest.java
src/test/java/com/artipie/http/auth/PermissionsTest.java

Closes #244 
Made `Identities`, `Permission` and `Permissions` work with `Authentication.User` instead of user name.

#244 - work with Authentication.User instead of username

---

src/main/java/com/artipie/http/hm/SliceHasResponse.java
src/main/java/com/artipie/http/rs/CachedResponse.java
src/test/java/com/artipie/http/rs/CachedResponseTest.java
src/test/java/com/artipie/http/rs/common/RsJsonTest.java
src/test/java/com/artipie/http/rs/common/RsTextTest.java

Closes #251 
`StatefulResponse` renamed to `CachedResponse` and changed to keep copy of body

#251 - StatefulResponse renamed to CachedResponse and fixed

---

src/main/java/com/artipie/http/auth/AuthScheme.java
src/test/java/com/artipie/http/auth/AuthSchemeNoneTest.java

#261 
Added absent auth scheme that is useful as `AuthScheme` implementation when no auth is required.

#261 - Added absent auth scheme

---

src/main/java/com/artipie/http/rs/RsFull.java
src/main/java/com/artipie/http/rs/RsWithBody.java
src/test/java/com/artipie/http/rs/RsFullTest.java

Closes #275 
Content constructors in `RsWithBody` and `RsFull`

#275 - Content constructors in RsWithBody and RsFull

---

src/test/java/com/artipie/http/slice/ContentWithSizeTest.java

Fixes #293 - using `content-length` instead of `content-size` in
ContentWithSize class, added a test.

Fixed ContentWithSize using correct header name

---

src/main/java/com/artipie/http/rq/RqParams.java
src/main/java/com/artipie/http/servlet/ServletSliceWrap.java
src/test/java/com/artipie/http/servlet/ServletWrapITCase.java

Fixes #295 - reproduced with a test by passing query params to
request URI, and fixed by passing query params to slice from servlet
wrapper. Found and fixed a bug with query params decoding,
added more tests for slice wrapper.

Pass query params from servlet request to slice

---

src/main/java/com/artipie/http/rs/RsWithBody.java
src/main/java/com/artipie/http/rs/RsWithHeaders.java
src/test/java/com/artipie/http/rs/RsWithBodyTest.java
src/test/java/com/artipie/http/rs/RsWithHeadersTest.java

Closes #305 
Added `override` parameter to `RsWithHeaders`: if this parameter is true, origin header values are replaced with provided headers values. This feature is now used in `RsWithBody` to avoid `Content-Length` header duplication/mismatch.

Added `override` parameter to `RsWithHeaders`

---

pom.xml
src/main/java/com/artipie/http/hm/IsJson.java
src/test/java/com/artipie/http/hm/IsJsonTest.java

For #324 - added JSON response matcher accepting
`? extends JsonStructure` - it's either `JsonObject` or
`JsonArray`. Added tests for matcher.

Response matcher for JSON

---

src/main/java/com/artipie/http/rq/multipart/MultiPart.java
src/main/java/com/artipie/http/rq/multipart/MultiParts.java
src/main/java/com/artipie/http/rq/multipart/State.java
src/test/java/com/artipie/http/misc/ByteBufferTokenizerTest.java
src/test/java/com/artipie/http/rq/multipart/MultiPartTest.java
src/test/java/com/artipie/http/rq/multipart/RqMultipartTest.java

Fix #380 by emmiting empty buffer to body downstrea publisher
if upstream was completed without delivering any chunk.
Fix #381 by prepanding initial chunk with `\r\n` to pass
preamble validation by emitting empty preamble to tokenizer.

fix: multipart request body parsing

---

pom.xml
src/main/java/com/artipie/http/rq/multipart/MultiPart.java
src/main/java/com/artipie/http/rq/multipart/State.java
src/test/java/com/artipie/http/rq/multipart/MultiPartTest.java
src/test/java/com/artipie/http/rq/multipart/MultipartITCase.java
src/test/java/com/artipie/http/rq/multipart/StateTest.java

Add integration test for multipart using Vertx server deployment
and apache-httpclient as client. The test sends request with multipart
body and slice handler parses this request and save expected part body,
then test compares expected part with data sent.
Fixed the problem discovered during testing: some clients don't respect
`RFC6838` specification of media types by expecting **case-sensitive**
mime-type param values for boundary param (it's not case sensitive by spec).
To fix this, the feature g4s8/mime#36 was added to mime-type parser and
a new version v2.3.0 was released.
Close: #420

test(multipart): integration test for multipart

---

src/main/java/com/artipie/http/rq/multipart/MultiPart.java

Try to fix `RejectedExecutionException` in pypi adapter by using shared cached thread pool
instead of single thread executor per multipart processor, do not shutdown it on complete.
Ref: artipie/artipie#1000

fix: use shared thread pool for multipart

---

src/main/java/com/artipie/http/auth/BasicAuthScheme.java
src/test/java/com/artipie/http/auth/BasicAuthSliceTest.java

According to RFC7617, the 'realm' parameter is REQUIRED(https://www.rfc-editor.org/rfc/rfc7617.html#section-2)

fix: add realm to WWW-Authenticate header

---

src/main/java/com/artipie/http/headers/Accept.java
src/test/java/com/artipie/http/headers/AcceptTest.java

fix: skip Accept header parsing in case no Accept headers presented

---

pom.xml
src/main/java/com/artipie/security/perms/AdapterAllPermissionFactory.java
src/main/java/com/artipie/security/perms/AdapterBasicPermission.java
src/main/java/com/artipie/security/perms/AdapterBasicPermissionFactory.java
src/main/java/com/artipie/security/perms/PermissionConfig.java
src/main/java/com/artipie/security/perms/PermissionFactory.java
src/main/java/com/artipie/security/perms/PermissionsLoader.java
src/main/java/com/artipie/security/policy/CachedYamlPolicy.java
src/main/java/com/artipie/security/policy/PoliciesLoader.java
src/test/java/adapter/perms/docker/DockerPermsFactory.java
src/test/java/adapter/perms/duplicate/DuplicatedDockerPermsFactory.java
src/test/java/adapter/perms/maven/MavenPermsFactory.java
src/test/java/com/artipie/security/perms/PermissionConfigYamlTest.java
src/test/java/com/artipie/security/perms/PermissionsTest.java
src/test/java/com/artipie/security/policy/CachedYamlPolicyTest.java

part of #501 
Docker permissions format includes resource (images name) and thus has more levels in yaml setting format:
```yaml
docker_repository_permission:
my-docker:
my-alpine: # resource (image) name
- pull
ubuntu-slim:
- pull
- push
docker-global:
*:
- pull
docker_registry_permission:
my-docker:
- catalog
- base
```
To parse such config and create permission we need to parse this yaml differently as yaml for `adapter_basic_permission`. In order to do so, I've made two changes:
- `PermissionFactory` now can return permissions collection
-  `PermissionConfig` permission config can return sub-config
In other words, all the changes are required as there can be only one `AdapterBasicPermission` for one repository, but in docker there can be several `DockerPermission` for one repository. …

feat: factory should return collection
